### PR TITLE
Nix mention of CoffeeScript

### PR DESCRIPTION
**Pull request by adamhooper**
CoffeeScript is vehemently anti-getters, so the reference to CoffeeScript is unhelpful here.

Ref: https://github.com/jashkenas/coffeescript/issues/1165#issuecomment-809691

### CODE REVIEW

**Comment by joshperry** [comment]
I'm pretty sure this feature was added specifically to mesh stylistically with parameterized method calls in tests written in CoffeeScript. Not because the getters are idiomatic per se, but because CoffeeScripters love eliding parens and parameterless methods can not be executed when doing this because it is ambiguous to the parser.

Example:

```
bar.is.not.empty
bar.equals 'foo'
```

vs

```
bar.is.not.empty()
bar.equals 'foo'
```

Though perhaps minutiae like this is better left in the sands of time...

**Comment by adamhooper** [comment]
Er ... I've coded CoffeeScript for years (for money) and in all that time, I never got the impression that Chai was influenced by CoffeeScript. [Chai's creator](https://github.com/logicalparadox?tab=repositories) doesn't seem to have written any CoffeeScript, ever.

CoffeeScript [hates](https://github.com/jashkenas/coffeescript/issues/2878#issuecomment-15339128) [getters](https://github.com/jashkenas/coffeescript/issues/64#issuecomment-106716). CoffeeScript makes it more difficult than JavaScript to implement getters. Simply put, getters are not a thing in CoffeeScript. The only exception is Chai. Chai is about as far from idiomatic CoffeeScript as you can be. CoffeeScript code that uses Chai is unlike any other CoffeeScript code.

That's what's so great about this project. It's like Chai ... without silliness. The README seems to advertise that CoffeeScripters should stay away ... when CoffeeScripters stand to gain the most from this library.

**Comment by joshperry** [comment]
Interesting. I'm definitely not interested in arguing the point as I honestly don't remember where I got this impression. I don't think removing the CoffeeScript reference is going to materially affect dirty-chai so I'll defer and merge this.

I am curious though, as I don't use CoffeeScript myself, how does this plugin benefit its users?

**Comment by adamhooper** [comment]
Thanks!

It benefits CoffeeScript users the same way it benefits JavaScript users. The difference, to me, is that JavaScript-ish libraries sometimes use getters; CoffeeScript-ish libraries never do.

**Pull request merged**
